---
# Jekyll options.
name: Site Name
domain: https://razor-x.github.io
baseurl: /jekyll-and-zurb
markdown: redcarpet
highlighter: pygments

# Uncomment below to enable pagination.
# paginate: 5

exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - VERSION
  - Gemfile.lock
  - Gemfile
  - Guardfile
  - Rakefile
  - bower.json
  - bower_components
  - node_modules
  - vendor

livereload:
  port: 35729

gems:
  - json
  - jekyll-assets
  - coffee_script

# Jekyll::AssetsPlugin options.
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  compress:
    css: sass
    js: uglifier
  autosize: true

# Use a CDN to load some libraries.
# Libraries are loaded first, asynchronously,
# and should not depend on each other.
cdn_enabled: true
cdn:
  # [ url, loaded check, local asset fallback path ]
  libs:
    - [ "https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js", "window.jQuery", "jquery/dist/jquery" ]

# Keywords will be merged with categories, tags, and page keywords.
keywords: [ blog, personal ]

# Uncomment below to set default meta info.
meta:
  locale: en_US
  description: "Jekyll skeleton built on Foundation."
  title:
    prefix: ""
    suffix: " -  Jekyll &amp; ZURB"
  twitter:
    default_card: summary
    site: "@evansosenko"
    creator: "@evansosenko"

# Uncomment below and add your Disqus Shortname to enable Disqus.
# disqus: shortname

# Uncomment below and add your Tracking ID and URL to enable Google Analytics.
google_analytics:
  id: UA-19631381-4
  url: evansosenko.com

# Uncomment below and add your Piwik URL to enable Piwik.
# piwik: https://example.com/piwik/

# Uncomment below to enable deploy.
# deploy:
#   # only :rsync supported
#   protocol: :rsync
#   # domain name
#   server: example.com
#   # remote username
#   user: www
#   # remote port
#   port: 22
#   # path to remote folder where contents of _site should go
#   # must have trailing slash
#   path: /var/www/example.com/htdocs/
#   # site files and folders that should be uploaded but not synced
#   # remote content will not be removed from these files and folders
#   upload_only:
#     - content/

# Foundation Interchange markup support added to
# Jekyll Picture Tag (https://github.com/robwierzbowski/jekyll-picture-tag)
# Uncomment below to enable responsive images.
# picture:
#   markup: 'interchange'
#   source: pictures/fullsize
#   output: pictures
#   presets:
#     default:
#       ppi: [ 1, 1.5, 2 ]
#       source_large:
#         media: '(large)'
#         width: '1440'
#       source_medium:
#         media: '(medium)'
#         width: '1280'
#       source_small:
#         media: '(small)'
#         width: '768'
#       source_default:
#         width: '500'

# Uncomment below to configure social media.
social:
  facebook:
    enabled: true
  google:
    enabled: true
    gcfg:
      lang: en-US
      parsetags: onload
  twitter:
    enabled: true
